pool:
  name: windows-2019
  demands: npm

trigger:
  - ng-msg-14

steps:
  - task: Npm@1
    displayName: "Install Packages"
    inputs:
      command: "install"
      workingDir: "./angular/ng-msg"
      verbose: true

  - powershell: |
      git config --global user.email "developer@bayestech.com.au"
      git config --global user.name "BayesTech-CI"

      npm run release

      cat projects/ng-msg/package.json
    workingDirectory: "./angular/ng-msg"
    displayName: "Update version"

  - task: Npm@1
    displayName: "Install Angular Cli"
    inputs:
      command: custom
      verbose: true
      customCommand: "install -g @angular/cli"

  - task: Npm@1
    displayName: Build
    inputs:
      command: custom
      workingDir: "./angular/ng-msg"
      verbose: true
      customCommand: "run build --prod ng-msg"

  - task: Npm@1
    inputs:
      command: "publish"
      workingDir: "./angular/ng-msg/dist/ng-msg"
      publishRegistry: useExternalRegistry
      publishEndpoint: "NPM"
      verbose: true

  - task: PowerShell@2
    inputs:
      targetType: "inline"
      script: |
        $version = (Get-Content projects/ng-msg/package.json) -join "`n" | ConvertFrom-Json | Select -ExpandProperty "version"
        git tag ng-msg-$version
        git push ng-msg-$version
        git push  https://$(GITHUB_USERNAME):$(GITHUB_PASSWORD)@github.com/BayesTech/msg.git --follow-tags HEAD:$(Build.SourceBranchName)
